### ISSUE TITLE
Buddyboss Support

### ISSUE THREAD

**Issue by LukeStaszewski** [mybytecode/flutter_blog#1]
Hello :) awesome app you've got here!

I've been looking for a Flutter solution that supports Buddyboss and there's really not much available right now. I'm thinking of building something myself - and this would be a great starting point.

Would you be open to me utilizing this as a template for the project?

I would like to release it open source if possible, but depending on the complexity, I might have to hire developers and maybe sell it to regain some profit, I'm not sure. Could we chat about the options? Maybe we could work together and sell it together?  I much prefer to release things open source and free, but sometimes it's just not financially possible.

Would love to talk to you,
Kind regards,
Luke

**Comment by LukeStaszewski** [comment]
@mybytecode

**Comment by mybytecode** [comment]
> @mybytecode

Hello Luke, please contact me at akshay@mybytecode.com

**Comment by mybytecode** [comment]
> @mybytecode

Hello Luke, please contact me at akshay@mybytecode.com

**Comment by mybytecode** [comment]
@LukeStaszewski

**Comment by LukeStaszewski** [comment]
@mybytecode emailed 👍
